services:
  zombierelay:
    image: alpine:latest
    ports:
      - "2224:22"
      - "9090:9090"
    volumes:
      - ./sshd_config:/tmp/sshd_config
    command: >
      sh -c "
      echo 'Installing OpenSSH...';
      apk update && apk add --no-cache openssh && \
      if [ ! -f /root/.ssh/id_ed25519 ]; then
        echo 'Generating SSH keys...';
        ssh-keygen -t ed25519 -N '' -f /root/.ssh/id_ed25519 -C '';
        cat /root/.ssh/id_ed25519.pub >> /root/.ssh/authorized_keys;
        chmod 600 /root/.ssh/authorized_keys;
      else
        echo 'SSH key already present. Not generating new ones.';
      fi;
      echo 'Run this command to extract the private key: docker cp $(docker ps -l -q):/root/.ssh/id_ed25519 .';
      cp /tmp/sshd_config/sshd_config /etc/ssh/sshd_config;
      echo 'Copied sshd_config into /etc/sshd_config.';
      echo 'Creating host keys and starting SSH server.';
      ssh-keygen -A && \
      /usr/sbin/sshd -D"
    stdin_open: true
    tty: true
